### ISSUE TITLE
Promise.all()

### ISSUE THREAD

**Issue by jvanbrunt** [malcommac/Hydra#12] opened 2017-02-21 16:29 UTC
Promise.all is throwing a no member all error.

```
import Hydra 

Promise.all(promises).then({
})

```

**Comment by malcommac** [comment] 2017-02-21 16:38
Hi thank you for your report. It's a duplicate of #11.
It has solved with 0.9.2 I'll release later this week.

**Closed** 2017-02-21 16:38 UTC
Labels: duplicate
